Repository efrei-craft/ECATUP, pull requests merged in 2022-11, with the labels that each got.

#24 Some fixes
  .github/release-drafter.yml
  .github/workflows/gradle.yml
  .github/workflows/release-drafter.yml
  README.md
  build.gradle
  exemple1.png
  src/main/java/fr/efreicraft/ecatup/commands/Chat.java
  src/main/java/fr/efreicraft/ecatup/utils/Msg.java
  src/main/resources/plugin.yml
Labels: bug, documentation, new stable version

#26 Add more categories to Release Drafter
  .github/release-drafter.yml
Labels: bug

#28 Bump -> 1.0.10
  README.md
  build.gradle
  src/main/java/fr/efreicraft/ecatup/Main.java
  src/main/java/fr/efreicraft/ecatup/commands/Chat.java
  src/main/java/fr/efreicraft/ecatup/commands/Gmc.java
  src/main/java/fr/efreicraft/ecatup/commands/Gms.java
  src/main/java/fr/efreicraft/ecatup/commands/Gmsp.java
  src/main/java/fr/efreicraft/ecatup/commands/WhoIs.java
  src/main/java/fr/efreicraft/ecatup/listeners/Join.java
  src/main/java/fr/efreicraft/ecatup/listeners/LuckPermsListener.java
  src/main/java/fr/efreicraft/ecatup/utils/DBConnection.java
  src/main/java/fr/efreicraft/ecatup/utils/DiscordWebhook.java
  src/main/java/fr/efreicraft/ecatup/utils/Msg.java
Labels: bug, new stable version, chore

#33 Changement de variable (de rôles*****)
  README.md
  build.gradle
  src/main/java/fr/efreicraft/ecatup/commands/Slap.java
  src/main/java/fr/efreicraft/ecatup/listeners/Join.java
Labels: bug, chore
